lib/airbnb_web/router.ex
defmodule AirbnbWeb.Router do
  use AirbnbWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {AirbnbWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AirbnbWeb do
    pipe_through :browser

    get "/", PageController, :index

    live "/properties/:id/photos", PropertyPhotosLive
    live "/properties/:id/map", PropertyMapLive
    live "/properties/checkin", PropertyCheckinLive

    get  "/properties", PropertyController, :index
    get  "/properties/new", PropertyController, :new
    get  "/properties/:id", PropertyController, :show
    post "/properties", PropertyController, :create
    get  "/properties/:id/edit", PropertyController, :edit
    put  "/properties/:id", PropertyController, :update
    delete "/properties/:id", PropertyController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", AirbnbWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: AirbnbWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/airbnb_web/views/layout_view.ex
defmodule AirbnbWeb.LayoutView do
  use AirbnbWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/airbnb_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/airbnb_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/airbnb_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <.live_title><%= assigns[:page_title] || "Airbnb" %></.live_title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header class="p-4">
      <section class="container">
        <nav class="flex p-4">
          <a href="/" class="phx-logo w-1/3 flex items-center justify-start">
            <img src={Routes.static_path(@conn, "/images/airbnb-ar21.svg")} alt="Airbnb Clone"/>
          </a>
          <ul class="w-2/3 flex space-x-4 items-center justify-end">
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home), class: "button-red" %></li>
            <% end %>
            <li><%= link "Properties", to: Routes.property_path(@conn, :index), class: "button-red" %></li>
            <li><%= link "Check In/Out", to: Routes.live_path(@conn, AirbnbWeb.PropertyCheckinLive), class: "button-red" %></li>
          </ul>
        </nav>
      </section>
    </header>
    <div class="p-4">
      <%= @inner_content %>
    </div>
  </body>
</html>